name: Caller Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  use-reusable:
    uses: abdulrohman6999/Example-Reusable-Workflow/.github/workflows/ci.yml@main
    with:
      environment: production
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
