name: Caller Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  use-reusable:
    uses: abdulrohman6999/Example-Reusable-Workflow/.github/workflows/ci.yml@main
    with:
      environment: production
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
